export const ratings = [
  {
    id: 1,
    name: "Pankaj Yadav",
    date: "30-11-2022",
    location: "Gurgaon",
    star: 5,
    review: "Easy and prompt",
  },
  {
    id: 2,
    name: "Swati Kumari",
    date: "29-11-2022",
    location: "Noida",
    star: 2,
    review: "He did rash driving. Not a good experience!",
  },
  {
    id: 3,
    name: "Ruchi Seth Trehan",
    date: "28-11-2022",
    location: "Noida",
    star: 4,
    review: "Driver was on time and drive well. Was polite.",
  },
  {
    id: 4,
    name: "Anamika Mittal",
    date: "30-11-2022",
    location: "Gurgaon",
    star: 4,
    review: "On Time. Value for money.",
  },
  {
    id: 5,
    name: "Pankaj Yadav",
    date: "30-11-2022",
    location: "Gurgaon",
    star: 5,
    review: "Easy and prompt",
  },
  {
    id: 6,
    name: "Swati Kumari",
    date: "29-11-2022",
    location: "Noida",
    star: 2,
    review: "He did rash driving. Not a good experience!",
  },
  {
    id: 7,
    name: "Ruchi Seth Trehan",
    date: "28-11-2022",
    location: "Noida",
    star: 4,
    review: "Driver was on time and drive well. Was polite.",
  },
  {
    id: 8,
    name: "Anamika Mittal",
    date: "30-11-2022",
    location: "Gurgaon",
    star: 4,
    review: "On Time. Value for money.",
  },
  {
    id: 9,
    name: "Pankaj Yadav",
    date: "30-11-2022",
    location: "Gurgaon",
    star: 5,
    review: "Easy and prompt",
  },
  {
    id: 10,
    name: "Swati Kumari",
    date: "29-11-2022",
    location: "Noida",
    star: 2,
    review: "He did rash driving. Not a good experience!",
  },
  {
    id: 11,
    name: "Ruchi Seth Trehan",
    date: "28-11-2022",
    location: "Noida",
    star: 4,
    review: "Driver was on time and drive well. Was polite.",
  },
  {
    id: 12,
    name: "Anamika Mittal",
    date: "30-11-2022",
    location: "Gurgaon",
    star: 4,
    review: "On Time. Value for money.",
  },
  {
    id: 13,
    name: "Pankaj Yadav",
    date: "30-11-2022",
    location: "Gurgaon",
    star: 5,
    review: "Easy and prompt",
  },
  {
    id: 14,
    name: "Swati Kumari",
    date: "29-11-2022",
    location: "Noida",
    star: 2,
    review: "He did rash driving. Not a good experience!",
  },
  {
    id: 15,
    name: "Ruchi Seth Trehan",
    date: "28-11-2022",
    location: "Noida",
    star: 4,
    review: "Driver was on time and drive well. Was polite.",
  },
  {
    id: 16,
    name: "Anamika Mittal",
    date: "30-11-2022",
    location: "Gurgaon",
    star: 4,
    review: "On Time. Value for money.",
  },
];
